### ISSUE TITLE
[Bug] Importing from a Insomnia collection

### ISSUE THREAD

**Issue by rubnogueira** [usebruno/bruno#1024]
I'm trying to import an Insomnia collection, and I'm getting this validation error on developer tools. This file was exported from Insomnia.

```
ValidationError: items[41].request.body.graphql.variables must be a `string` type, but the final value was: `{}`.
    at Object.b [as createError] (_app-5953c08eb88e44dd.js:1:1145238)
    at Object.test (_app-5953c08eb88e44dd.js:1:1153120)
    at t (_app-5953c08eb88e44dd.js:1:1145739)
    at j (_app-5953c08eb88e44dd.js:1:1143306)
    at ne._validate (_app-5953c08eb88e44dd.js:1:1150667)
    at ne.validate (_app-5953c08eb88e44dd.js:1:1150894)
    at _app-5953c08eb88e44dd.js:1:1164325
    at j (_app-5953c08eb88e44dd.js:1:1143306)
    at _app-5953c08eb88e44dd.js:1:1164416
    at _app-5953c08eb88e44dd.js:1:1143177
```

**Comment by nelup20** [comment]
Perfect, thanks @rubnogueira! I was able to reproduce it, I'll work on it 👍
