### ISSUE TITLE
White screen while trying to delete a request or folder  when folder/collection run tab is open

### ISSUE THREAD

**Issue by andrii-lemdianov** [usebruno/bruno#1210]
Hi, 
I'm facing the issue - **White screen** - while trying to delete a request or folder  when folder/collection run tab is open

## Steps to Reproduce

1. Open or import any collection (e.g. https://github.com/usebruno/github-rest-api-collection)
2. Clone a single request or a folder 
3. Run a new folder or modified one
4. Attempt to remove a folder or a single request

## Expected Behavior

- A folder or a single request successfully removed 

## Actual Behavior

- **White screen** appeared and the only way to continue work - restart Bruno
- The following error is shown in the DevTool console
`{error: TypeError: Cannot read properties of undefined (reading 'name')
    at file:///Applications/Bruno%2…, errorInfo: {…}}
error
: 
TypeError: Cannot read properties of undefined (reading 'name') at file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/735-b84c189edc58c0d8.js:1:134919 at Ot (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f501db2fe71d320a.js:1:332867) at wa (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f501db2fe71d320a.js:1:369199) at mr (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/735-b84c189edc58c0d8.js:1:134867) at Eo (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:63194) at Pu (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:74882) at xi (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:121317) at bs (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109370) at gs (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109298) at vs (file:///Applications/Bruno%202.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109161)
errorInfo
: 
{componentStack: '\n    at mr (file:///Applications/Bruno%202.app/Con…t/static/chunks/main-ad5649da2d8f61d3.js:1:11344)'}
[[Prototype]]
: 
Object`

## Additional Information
OS: macOS Monterey,
App: Latest Version: [1.4.0](https://github.com/usebruno/bruno/releases/tag/v1.4.0), Mac Apple Silicon
Release Date: Dec 5, 2023
Electron: 21.1.1
Chrome: 106.0.5249.103
node: 16.16.0
v8: 10.6.194.17-electron
<img width="397" alt="image" src="https://github.com/usebruno/bruno/assets/60614852/b420698b-f75e-43ff-aa34-91525a83f2bf">
I made a short screen recording

https://github.com/usebruno/bruno/assets/60614852/a8e17a78-797c-4004-b8b5-b38cb46061c7

**Comment by mrp4sten** [comment]
I have the same problem but when a Request is failed from the server with status 500

**Comment by sanjai0py** [comment]
Closing the issue as the [PR](https://github.com/usebruno/bruno/pull/1213) fixing the bug has already been merged into Bruno.
