### ISSUE TITLE
[Bug] Unable to Generate Code

### ISSUE THREAD

**Issue by kasyauqi** [usebruno/bruno#1231]
Environment:
* Version: v1.4.0
* OS: Mac OS Sonoma (14.0 (23A344))
* CPU: M2 Max
* Bruno Installation via homebrew.

Everytime the "Generate Code" menu is opened, there'll be this error:

```
735-b84c189edc58c0d8.js:1 TypeError: Cannot read properties of undefined (reading 'filter')
    at Mo (735-b84c189edc58c0d8.js:1:205214)
    at Ko.Vo.HTTPSnippet.request (735-b84c189edc58c0d8.js:1:205743)
    at Ko (735-b84c189edc58c0d8.js:1:205780)
    at Eo (framework-49f1e091cbf6b261.js:1:63194)
    at xi (framework-49f1e091cbf6b261.js:1:120434)
    at bs (framework-49f1e091cbf6b261.js:1:109370)
    at gs (framework-49f1e091cbf6b261.js:1:109298)
    at vs (framework-49f1e091cbf6b261.js:1:109161)
    at is (framework-49f1e091cbf6b261.js:1:106277)
    at jl (framework-49f1e091cbf6b261.js:1:46915)
Ko @ 735-b84c189edc58c0d8.js:1
Eo @ framework-49f1e091cbf6b261.js:1
xi @ framework-49f1e091cbf6b261.js:1
bs @ framework-49f1e091cbf6b261.js:1
gs @ framework-49f1e091cbf6b261.js:1
vs @ framework-49f1e091cbf6b261.js:1
is @ framework-49f1e091cbf6b261.js:1
jl @ framework-49f1e091cbf6b261.js:1
(anonymous) @ framework-49f1e091cbf6b261.js:1
```

<img width="1510" alt="image" src="https://github.com/usebruno/bruno/assets/35339552/d4ac9964-d8eb-4f55-99d9-1c7c75d087a6">

**Comment by mj-h** [comment]
Can you try with 1.5.1? It works for me...

**Comment by survivant** [comment]
can you check on my branch .  I did some improvments https://github.com/survivant/bruno/tree/BrunoSD
