### ISSUE TITLE
Environment pop-in crash on click

### ISSUE THREAD

**Issue by PierreLbg** [usebruno/bruno#1313]
Bruno version: 1.5.1
System: Windows

At a first time I have this environment pop-in. It's working totally fine.
![environnement](https://github.com/usebruno/bruno/assets/50985406/9b1d9581-dee0-44c1-9a03-50699ef05e80)

But after running a query with this post response script:
![image](https://github.com/usebruno/bruno/assets/50985406/f9852c58-d2fb-4528-977e-495371f8a952)

Wich is just setting the environment variable entityId to 6

The configuration button won't work
![image](https://github.com/usebruno/bruno/assets/50985406/1203fc34-5ad4-4d0c-9f8b-2bbfb789a52c)
and end up with this error
![image](https://github.com/usebruno/bruno/assets/50985406/243d5559-c00e-4ea2-ac40-cd735ce355fb)

Full error message:
> TypeError: e.split is not a function
>     at Ne (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:83864)
>     at ka.splitLines (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:182038)
>     at ka.<anonymous> (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:174376)
>     at ka.setValue (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:139791)
>     at qs.setValue (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:245487)
>     at r.value (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/pages/_app-5953c08eb88e44dd.js:1:502622)
>     at ki (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:101099)
>     at bi (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:100872)
>     at yi (file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:100408)
>     at file:///PATH_TO_BRUNO_LOCATION/bruno/resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:112245

Nota bene:
My variable is correctly set.
![image](https://github.com/usebruno/bruno/assets/50985406/782f0cb1-27a1-465f-aa3b-0e70b5f513f7)
And I can use it 
![image](https://github.com/usebruno/bruno/assets/50985406/92a85a3f-04b1-435f-ae57-974ff422382c)

But it's not set in my .bru file
![image](https://github.com/usebruno/bruno/assets/50985406/ff4d32e8-f795-432e-b0e9-6d5b19da9e4e)

**Comment by PierreLbg** [comment]
Environment value don't work with number using string solve the issue
