### ISSUE TITLE
unspecified keys: docs 

### ISSUE THREAD

**Issue by SiggiSmara** [usebruno/bruno#1614]
Hello,

For some time now I have gotten an error when importing a collection via a json file: 
```
validationError: items[5].items[0].items[0] field has unspecified keys: docs
    at Object.b [as createError] (_app-766251f41170d742.js:1:1173828)
    at Object.test (_app-766251f41170d742.js:1:1194999)
    at t (_app-766251f41170d742.js:1:1174329)
    at j (_app-766251f41170d742.js:1:1171896)
    at _app-766251f41170d742.js:1:1179323
    at _app-766251f41170d742.js:1:1171767
    at _app-766251f41170d742.js:1:1172093
    at _app-766251f41170d742.js:1:1174372
```
This comes as there is a "docs"  element present for some items, the very same that is used by Bruno to store what is written in the docs tab for the API.

I've also noticed when a collection is exported then no "docs" elements are exported.

The same collection as is encoded in the json file works as expected, including the "docs" elements, when opened as a folder system.

Also adding documentation inside of Bruno works as expected in that it saves the entered text in a "docs" element of the individual .bru file.

**Comment by SiggiSmara** [comment]
Sorry, my bad, finally found the error in the import json.  But the "docs" items are still not exported. I'll close this issue and create another one specifically for that
