### ISSUE TITLE
BUG: OAuth2 Authorization Code Flow fails for intermediate redirects

### ISSUE THREAD

**Issue by layereight** [usebruno/bruno#1778]
The authorization process will fail for authorization servers offering a "multi-step" authorization that include intemediate redirects casually containing the keyword `code` in their uri.

I happen to use an authorization server that guides the user through several forms (connected through intemediate redirects) during the authorization process. One of the intermediate redirect casually contains `code` in the uri (but not as the distinct query parameter). Thus the authorization code flow fails with the following error trace:

```
Error occurred in handler for 'send-http-request': Error: Invalid Callback Url
    at onWindowRedirect (~/devel/bruno/packages/bruno-electron/out/linux-unpacked/resources/app.asar/src/ipc/network/authorize-user-in-window.js:30:18)
    at EventEmitter.didNavigateListener (~/devel/bruno/packages/bruno-electron/out/linux-unpacked/resources/app.asar/src/ipc/network/authorize-user-in-window.js:67:7)
    at EventEmitter.emit (node:events:527:28)
```

**Comment by layereight** [comment]
The issue still exists with release 1.11.0

**Comment by ThomasPilot** [comment]
> The issue still exists with release 1.11.0

Can confirm this, same issue here.
