### ISSUE TITLE
"Minified Redux Error" After Installing v1.12.1 When Attempting to Re-order Collections Alphabetically

### ISSUE THREAD

**Issue by Arnaldino** [usebruno/bruno#1850]
Hi team and @helloanoop, hope you are well and congrats for Golden Edition release.

There is a small issue when attempting to re-order collection alphabetically after v1.12.1 install. I installed it over v1.

I also did a refresh install, the same was happening too.

Config:

Mac M1.
Used the bruno_1.12.1_arm64_mac to install.

<img width="930" alt="97290" src="https://github.com/usebruno/bruno/assets/39277295/b8ed3662-416c-4cdf-aa3c-9e1c539a2f14">

<img width="1372" alt="14862" src="https://github.com/usebruno/bruno/assets/39277295/b87035df-60a9-4dd9-9080-b29af2156cfa">

<img width="1051" alt="94835" src="https://github.com/usebruno/bruno/assets/39277295/0e066716-2d1a-4ed1-8129-f07b2f573a75">

```
Error: Minified Redux error #8; visit https://redux.js.org/Errors?code=8 for the full message or use the non-minified dev environment for full errors. 
    at g (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1ccb54918d40d9bf.js:1:1159408)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1ccb54918d40d9bf.js:1:26158
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1ccb54918d40d9bf.js:1:10409
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/972-4d6d61501f147946.js:1:305329
    at onClick (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/972-4d6d61501f147946.js:1:305342)
    at Object.Oe (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:16876)
    at Ae (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:17030)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:36930
    at Ir (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:37024)
    at Ur (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:37439)
    ```

**Comment by Arnaldino** [comment]
Solved in 1.12.2. Closing this.
