### ISSUE TITLE
Can't Import Bruno Collection On latest Version

### ISSUE THREAD

**Issue by Flo4604** [usebruno/bruno#1868]
1. Updated to version v1.12.1

2. Exported Bruno Collection
3. Tried importing 
4.  Getting the following error:
<img width="539" alt="6844" src="https://github.com/usebruno/bruno/assets/53355483/9f9119da-79b7-44df-9ba2-584f98ce3450">

Bruno Collection: [Test.zip](https://github.com/usebruno/bruno/files/14670951/Test.zip)
Export: [test_import.json](https://github.com/usebruno/bruno/files/14670954/test_import.json)

**Comment by JSSAggie** [comment]
I have been struggling with getting postman collections to import with the version I installed today.

```
_app-1ccb54918d40d9bf.js:1 Warning: An unhandled error was caught from submitForm() ReferenceError: enableTranslation is not defined
    at handleSubmit (972-4d6d61501f147946.js:1:33071)
    at onSubmit (972-4d6d61501f147946.js:1:30860)
    at _app-1ccb54918d40d9bf.js:1:301319
    at _app-1ccb54918d40d9bf.js:1:303965
    at _app-1ccb54918d40d9bf.js:1:300594
```

Not sure if it is related?

**Comment by JSSAggie** [comment]
> I have been struggling with getting postman collections to import with the version I installed today.
> 
> ```
> _app-1ccb54918d40d9bf.js:1 Warning: An unhandled error was caught from submitForm() ReferenceError: enableTranslation is not defined
>     at handleSubmit (972-4d6d61501f147946.js:1:33071)
>     at onSubmit (972-4d6d61501f147946.js:1:30860)
>     at _app-1ccb54918d40d9bf.js:1:301319
>     at _app-1ccb54918d40d9bf.js:1:303965
>     at _app-1ccb54918d40d9bf.js:1:300594
> ```
> 
> Not sure if it is related?

Ignore that one is logged here https://github.com/usebruno/bruno/issues/1855

**Comment by taylorwhipp-gp** [comment]
For what it's worth, I'm using the desktop version and was unable to get a postman collection to import on the main screen, but when i navigated to the ellipsis menu I was able to import collections from there. 

Not sure if that helps your use case.

**Comment by gdnthomas** [comment]
Duplicate of https://github.com/usebruno/bruno/issues/1855

**Comment by Flo4604** [comment]
> Duplicate of https://github.com/usebruno/bruno/issues/1855

The issue I reported is not the same error as #1855, the comments afterwards are.

**Comment by rlabrecquefsg** [comment]
I was hitting this as well; this comment by taylorwhipp-gp worked for me. Though as a brand new user I find it quite concerning from like a code architecture/quality standpoint that opening the same dialog from a different location produces a different result, as well as the very first action I performed not working.

https://github.com/usebruno/bruno/issues/1868#issuecomment-2015873619

**Comment by Flo4604** [comment]
> I was hitting this as well; this comment by taylorwhipp-gp worked for me. Though as a brand new user I find it quite concerning from like a code architecture/quality standpoint that opening the same dialog from a different location produces a different result, as well as the very first action I performed not working.
> 
> [#1868 (comment)](https://github.com/usebruno/bruno/issues/1868#issuecomment-2015873619)

Then the code for exporting a bruno collection must be cached too. 

When importing a collection it must be of type http-request: https://github.com/usebruno/bruno/blob/50e3943fb11dba5c5990d7986a97842fb599e854/packages/bruno-schema/src/collections/index.js#L234

The exported JSON contains the type http not http-request: 
<img width="145" alt="94553" src="https://github.com/usebruno/bruno/assets/53355483/70757498-09cd-463b-9dbe-5b5383e41b22">

so I assume the export uses and old cached version, ill see if i can get a workaround and look into the code too.

**Comment by Its-treason** [comment]
Seems to be fixed with 1.12.3

**Comment by armdab** [comment]
Hello
I have same error after updating Bruno on 1.12.3 Mac x64 version.
To replicate this issue you need to  export a Bruno collection and  Import same Bruno collection.

<img width="956" alt="Capture d’écran 2024-04-10 à 18 11 55" src="https://github.com/usebruno/bruno/assets/45043209/478d28c5-02b7-480b-b6c7-c17125f5c5fa">

**Comment by samc-vaarst** [comment]
Same issue here

**Comment by armdab** [comment]
it's a big issues due our workflow. Please team, take for next release. Thanks

**Comment by philippgille** [comment]
Getting the same error as in OP's screenshot in 1.13.1

**Comment by armdab** [comment]
@sanjai0py any planed fix? I am blocked when importing Bruno collections... thanks

**Comment by Flo4604** [comment]
upgrade to latest version and tried again issue is still there

**Comment by Liamhhhhh** [comment]
Have you tried importing [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)? I tried it and encountered no issues. I'll be using it as a temporary replacement. 
﻿ 
﻿

**Comment by rrusher** [comment]
v1.29.1
Fails to import Bruno collection.

bruno.json
```
{
  "version": "1",
  "name": "site-configuration",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}
```
![image](https://github.com/user-attachments/assets/cc0dba37-7bfa-4b09-925c-9c6fe36edc06)

**Comment by sanjai0py** [comment]
Hey @rrusher, will you be able to share the Bruno Collection JSON that you're trying to import into Bruno?

**Comment by jrmcdonald-waitrose** [comment]
I can reproduce this whilst trying to import a collection that only has this bruno.json file in it:

```
{
  "version": "1",
  "name": "Personal",
  "type": "collection",
  "ignore": [
    "node_modules",
    ".git"
  ]
}
```

Debugging the ValidationError in the dev tools suggests that it thinks the `type` and `ignore` keys are unknown. These were generated by Bruno when I created the collection.

**Comment by naman-bruno** [comment]
Hey, I’m closing this since the issue hasn’t occurred in a long time. If anyone encounters it again, please feel free to reopen it.
