### ISSUE TITLE
[Bruno Dev Tools][JSON Prettifier] `Unexpected end of JSON input` error

### ISSUE THREAD

**Issue by rachasakr** [usebruno/bruno#1876]
**Bruno version:** 1.12.2 Golden edition on Linux Mint

![image](https://github.com/usebruno/bruno/assets/27821769/a03b5683-464d-4af4-b5ec-dc3ea5df63ac)
![image](https://github.com/usebruno/bruno/assets/27821769/59df4bf7-65de-4ff3-9af4-c0fe76080017)

**Module:** Bruno Dev Tools > JSON Prettifier

**Error message:** SyntaxError: Unexpected end of JSON input

**Step to reproduce:**
1. Click menu (3 dots on the right of Bruno logo)
2. Click Bruno Dev Tools
3. Select `+ New` > Prettify JSON
4. Change from `2 Tab space` to `4 Tab Space`

**Full Error Message:**

```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at onClick (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/708-91b98ba4d9a5d350.js:1:376244)
    at Object.Nb (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:14966)
    at Tb (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:15120)
    at file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:33456
    at nf (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:33555)
    at se (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:33969)
    at file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:39424
    at Rk (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:96368)
    at Jb (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:14104)
```
![image](https://github.com/usebruno/bruno/assets/27821769/479b438d-cd52-43c5-a33a-a86e6751f15f)

**Comment by sanjai0py** [comment]
Hey @rachasakr, sorry for the inconvenience. Thanks for reporting the issue. We've fixed the bug and it will be released soon.

**Comment by sanjai0py** [comment]
Bug fixed in the latest release. Let us know if it still persists.
