### ISSUE TITLE
🐞 white screen on collection variables

### ISSUE THREAD

**Issue by josh-i386g** [usebruno/bruno#1940]
When I go to collection settings -> eye variables I get a white screen

electron	: 21.1.1
chrome	: 106.0.5249.103
node	: 16.16.0
v8	: 10.6.194.17-electron.0

![image](https://github.com/usebruno/bruno/assets/150557754/0b37d7f7-55ec-4e72-a837-8f2b9b1b9aa9)

**Comment by Its-treason** [comment]
Looks like the problem I encountered a few days ago during testing. I already fixed it on my fork. I'll open a PR for this in the evening.

**Comment by timwhite** [comment]
More debugging in #1968 for what appears to be the same issue

**Comment by mig8447** [comment]
[-1711824312867.log](https://github.com/usebruno/bruno/files/14813006/-1711824312867.log)

Adding log. Experiencing the exact same issue

**Comment by DanaEpp** [comment]
I am seeing this behavior as well with Bruno v1.12.3 on MacOS Sonoma 14.4.1. 

My only option is to force quit the app to recover.

Stacktrace error:
```
TypeError: n.map is not a function
    at KeyValueExplorer (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:181742)
    at Xh (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:60991)
    at x (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:119446)
    at Vk (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:99131)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:98998
    at Jk (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:99005)
    at Ok (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:95761)
    at Fk (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:96150)
    at jg (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:44900)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:93662
```

**Comment by npu78954** [comment]
Same bug here, here is the stack trace
![error](https://github.com/usebruno/bruno/assets/139650490/65931fc5-44e3-445c-949d-840a4c1dccb0)

**Comment by helloanoop** [comment]
Thanks for the PR @Its-treason !

Issue has been fixed.
This will go out in the `1.13.0` release. Please subscribe to [Discord](https://discord.com/invite/KgcZUncpjq) announcement channel to stay notified on the releases.
