### ISSUE TITLE
Crash when trying to view vars after saving a var post request

### ISSUE THREAD

**Issue by timwhite** [usebruno/bruno#1968]
Trying to post process some request data into a variable, was trying to save an array, then tried to save a JSON string, eventually tried to just save an empty string, all result in a crash when next attempting to open the view vars tab.

I have a console.log in the post script, which works fine, it just appears to be anything saved into the variables post request. This is from a graphql query.

Version 1.12.3 installed from deb package

Example config:
```
vars:post-response {
  toDelete: JSON.stringify("")
}

script:post-response {
  console.log(JSON.stringify(res.body.data.torrentContent.search.items.map(({ infoHash}) => infoHash)))
}

```

```
TypeError: n.map is not a function
    at KeyValueExplorer (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:181742)
    at Xh (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:60991)
    at x (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:119446)
    at Vk (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:99131)
    at file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:98998
    at Jk (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:99005)
    at Ok (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:95761)
    at Fk (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:96150)
    at jg (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:44900)
    at file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/framework-80ea8c0f440c6a32.js:9:93662
```

```json
{
    "componentStack": "\n    at KeyValueExplorer (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:181488)\n    at CollectionVariables (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:182805)\n    at div\n    at P (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:36:39282)\n    at components_VariablesEditor (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:183196)\n    at components_RequestTabPanel (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:262054)\n    at section\n    at div\n    at P (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:36:39282)\n    at div\n    at Main (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/951-d020733b4cdea97a.js:1:409674)\n    at main\n    at div\n    at Home\n    at div\n    at HotkeysProvider (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:54477)\n    at div\n    at P (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:36:39282)\n    at AppProvider (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:19:44887)\n    at GoldenEdtionGuardProvider (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:60875)\n    at div\n    at ToastProvider (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:19:46135)\n    at Le (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:36:37102)\n    at Theme (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:141630)\n    at components_Provider (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:29:3949)\n    at NoSsr (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:59416)\n    at div\n    at SafeHydrate (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:59312)\n    at ErrorBoundary (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:19:36153)\n    at _app (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/pages/_app-25eaa9987eeec13f.js:22:59546)\n    at _PathnameContextProviderAdapter (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:62713)\n    at Container (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:9068)\n    at AppContainer (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:11134)\n    at Root (file:///opt/Bruno/resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:14776)"
}
```

**Comment by Its-treason** [comment]
Duplicate of #1940

**Comment by timwhite** [comment]
@Its-treason You are probably correct. I was searching for the error messages in the issues, and couldn't find an existing issue. Looking forward to the fixing being merged.
