### ISSUE TITLE
Bruno Cli throwing UnhandledPromiseRejectionWarning 

### ISSUE THREAD

**Issue by spookfish** [usebruno/bruno#2144]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When installing Bruno like so:

```
npm install -g @usebruno/cli
```

And then running the command:

```
bru run
```

I get the following error:

```
$ bru run

Bru CLI 1.11.0
(node:61619) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:134
          const requestHasTests = bruJson.request?.tests;
                                                  ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Object.require (internal/modules/cjs/helpers.js:74:18)
    at /usr/local/lib/node_modules/@usebruno/cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (<anonymous>)
    at Object.requireDirectory (/usr/local/lib/node_modules/@usebruno/cli/node_modules/require-directory/index.js:59:24)
(node:61619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61619) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Details:
```
Linux ubuntults 6.5.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC 
Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

npm --version = 8.5.1
node --version = v12.22.9
```

### Screenshots/Live demo link

```
Bru CLI 1.11.0
(node:61619) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:134
          const requestHasTests = bruJson.request?.tests;
                                                  ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Object.require (internal/modules/cjs/helpers.js:74:18)
    at /usr/local/lib/node_modules/@usebruno/cli/node_modules/require-directory/index.js:76:17
    at Array.forEach (<anonymous>)
    at Object.requireDirectory (/usr/local/lib/node_modules/@usebruno/cli/node_modules/require-directory/index.js:59:24)
(node:61619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:61619) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Its-treason** [comment]
The error is complaining about the `?` / optional chaining operator, this feature is only available in Node v14+, see [node.green](https://node.green/#ES2020-features-optional-chaining-operator-----).

Try updating your Node version, Bruno only supports node v20 or v18.

**Comment by spookfish** [comment]
Excellent! I updated to the latest version of node and it working.
