### ISSUE TITLE
[BUG] Having query{} on a GET request makes bruno to not recognize changes on file

### ISSUE THREAD

**Issue by arturbacilla** [usebruno/bruno#2417]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

I have a shell script to generate .bru files automatically based on some conditions unsing some templates. By mistake I added in my template, in a GET request, a query{}. All my generated files then are not recognized in bruno list and when mistankenly adding query{} to a GET .bru, it stops recognizing changes on that file.

### .bru file to reproduce the bug

meta {
  name: getAllSomething
  type: http
  seq: 1
}

get {
  url: {{baseUrl}}/{{currModule}}/{{process.env.CLIENT_ID}}
  body: none
  auth: bearer
}

query {}

auth:bearer {
  token: {{authToken}}
}
vars:pre-request {
  currModule: some
}

### Screenshots/Live demo link

![image](https://github.com/usebruno/bruno/assets/58752851/018c050b-01df-4777-817e-3465c3e15477)
In this first image I have created a Test.bru with same structure but without query{}

![image](https://github.com/usebruno/bruno/assets/58752851/a237a217-ece0-42c8-83a4-4d8ca7624c18)
As you can see, the getAll... is not listed on bruno interface

![image](https://github.com/usebruno/bruno/assets/58752851/6d2cb08f-8210-451d-99d7-6a823fbb90d5)

But as soon as I remove it (and reload bruno) it displays correctly

I was not able to add a video here, but if I add by mistake the query{} and reload bruno it will display in the list BUT any other changes after will not be updated

**Comment by gemiusz** [comment]
Bruno: 1.18.1
System: Windows 11

I have reproduced this bug and make additional tests with other tags with value {} and for every it's same issue.
I think there should be some Error message like "File not opened because there is error in file filename.bru" to inform user about issue.

Below example of collection with most of tags  that can be used for testing this issue:
[GeMiusz_Bruno_BUGS_EmptyTags.zip](https://github.com/user-attachments/files/15686297/GeMiusz_Bruno_BUGS_EmptyTags.zip)

**Comment by sanjai0py** [comment]
Hey @gemiusz, could you please provide the tests specific to this issue? The collection you've shared includes tests that were meant for the performance aspect.

**Comment by gemiusz** [comment]
I have downloaded and rechecked added collection and this collection GeMiusz_Bruno_BUGS_EmptyTags have a loot of test cases (bru files) that have empty tags and they arent shown after import in bruno. There arent any message about errors... nothing. Only one proper bru file is shown.

![image](https://github.com/usebruno/bruno/assets/30750006/ef932ad4-40fe-491b-8211-956a2affe509)


When run from cmd I getting:

```terminal
---PROFILE_FOLDER---AppData\Local\Programs\bruno>
Preferences file is located at: ---PROFILE_FOLDER---AppData\Roaming\bruno\preferences.json
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\bruno.json
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\bruno.json.bak
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_bodyEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 15, col 1:
  14 |
> 15 |
       ^
Expected "\n"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(Use `Bruno --trace-warnings ...` to show where the warning was created)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_deleteEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 7, col 10:
  6 |
> 7 | delete {}
               ^
  8 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_getEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 7, col 7:
  6 |
> 7 | get {}
            ^
  8 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_getOK.bru
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_headersEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 13, col 11:
  12 |
> 13 | headers {}
                 ^
  14 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_metaEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 1, col 8:
> 1 | meta {}
             ^
  2 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_optionsEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 7, col 11:
  6 |
> 7 | options {}
                ^
  8 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_postEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 7, col 8:
  6 |
> 7 | post {}
             ^
  8 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_putEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 7, col 7:
  6 |
> 7 | put {}
            ^
  8 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
watcher add: ---COLLECTION_FOLDER---bruno\bruno_bugs\GeMiusz_Bruno_BUGS_EmptyTags\GeMiusz_queryEmpty.bru
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:253:23)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Error: Line 13, col 9:
  12 |
> 13 | query {}
               ^
  14 |
Expected ":"
    at parser (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\@usebruno\lang\v2\src\bruToJson.js:592:11)
    at bruToJson (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\bru\index.js:94:18)
    at add (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:249:19)
    at FSWatcher.<anonymous> (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\src\app\watcher.js:548:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:540:8)
    at FSWatcher._emit (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\index.js:632:8)
    at NodeFsHandler._handleFile (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (---PROFILE_FOLDER---AppData\Local\Programs\bruno\resources\app.asar\node_modules\chokidar\lib\nodefs-handler.js:637:21)
(node:13360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

```
