### ISSUE TITLE
Error importing Insomia collection

### ISSUE THREAD

**Issue by rsantellan** [usebruno/bruno#2699]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Importing a v4 Insomnia collection say it has an error and check the terminal.

```
[13646:0724/224449.673125:ERROR:mime_util_xdg.cc(137)] Invalid mime.cache file does not contain null prior to ALIAS_LIST_OFFSET=44
Error occurred in handler for 'renderer:import-collection': TypeError: Cannot read properties of undefined (reading 'includes')
    at getValueString (/opt/Bruno/resources/app.asar/node_modules/@usebruno/lang/v2/src/jsonToBru.js:16:29)
    at /opt/Bruno/resources/app.asar/node_modules/@usebruno/lang/v2/src/jsonToBru.js:266:49
    at Array.map (<anonymous>)
    at jsonToBru (/opt/Bruno/resources/app.asar/node_modules/@usebruno/lang/v2/src/jsonToBru.js:262:12)
    at jsonToBru (/opt/Bruno/resources/app.asar/src/bru/index.js:198:10)
    at /opt/Bruno/resources/app.asar/src/ipc/collection.js:579:29
    at Array.forEach (<anonymous>)
    at parseCollectionItems (/opt/Bruno/resources/app.asar/src/ipc/collection.js:577:15)
    at /opt/Bruno/resources/app.asar/src/ipc/collection.js:597:15
    at Array.forEach (<anonymous>)
    at parseCollectionItems (/opt/Bruno/resources/app.asar/src/ipc/collection.js:577:15)
    at /opt/Bruno/resources/app.asar/src/ipc/collection.js:654:13
    at async WebContents.<anonymous> (node:electron/js2c/browser_init:2:83254)
watcher add: ~/proyectos/Bruno/silex/bruno.json
watcher add: ~/proyectos/Bruno/silex/collection.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Contacto.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Datos de Interes.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Listado de archivos .bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Login MIO v2.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Login mtur.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Login pvainer.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Login rcabillon.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/Login.bru
watcher add: ~/proyectos/Bruno/silex/RDL V2/get a file.bru

```

### .bru file to reproduce the bug

[Insomnia_2024-07-24.json](https://github.com/user-attachments/files/16369202/Insomnia_2024-07-24.json)

### Screenshots/Live demo link

.

**Comment by Anutrix** [comment]
Same issue:
```
Error: Error invoking remote method 'renderer:import-collection': TypeError: Cannot read properties of undefined (reading 'includes')
(anonymous) @ 631-629f0c4465914202.js:1
Promise.catch (async)
handleSubmit @ 631-629f0c4465914202.js:1
onSubmit @ 631-629f0c4465914202.js:1
(anonymous) @ _app-0e183f60e7582c8e.js:6
(anonymous) @ _app-0e183f60e7582c8e.js:6
(anonymous) @ _app-0e183f60e7582c8e.js:6
Promise.then (async)
(anonymous) @ _app-0e183f60e7582c8e.js:6
(anonymous) @ _app-0e183f60e7582c8e.js:6
(anonymous) @ _app-0e183f60e7582c8e.js:6
(anonymous) @ _app-0e183f60e7582c8e.js:6
handleConfirm @ 631-629f0c4465914202.js:1
Nb @ framework-80ea8c0f440c6a32.js:9
Tb @ framework-80ea8c0f440c6a32.js:9
(anonymous) @ framework-80ea8c0f440c6a32.js:9
nf @ framework-80ea8c0f440c6a32.js:9
se @ framework-80ea8c0f440c6a32.js:9
(anonymous) @ framework-80ea8c0f440c6a32.js:9
Rk @ framework-80ea8c0f440c6a32.js:9
Jb @ framework-80ea8c0f440c6a32.js:9
hd @ framework-80ea8c0f440c6a32.js:9
fd @ framework-80ea8c0f440c6a32.js:9
ed @ framework-80ea8c0f440c6a32.js:9
```
