### ISSUE TITLE
Clicking on Test tab after running request crashes bruno

### ISSUE THREAD

**Issue by jhorton-netapp** [usebruno/bruno#2726]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

Attempting to create tests based on result of axios requests made in test script. The base request completes, and the test script runs, and the tests tab shows a red number (33) indicating that tests failed, but clicking on the tab crashes bruno. The dev console shows the following error 33 times (once for each test failure, presumably):
```
_app-9839c548e42fbab0.js:14 Object
framework-80ea8c0f440c6a32.js:9 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bmessage%2C%20name%2C%20stack%2C%20config%2C%20code%2C%20status%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at th (framework-80ea8c0f440c6a32.js:9:54340)
    at J (framework-80ea8c0f440c6a32.js:9:59348)
    at Yi (framework-80ea8c0f440c6a32.js:9:71191)
    at x (framework-80ea8c0f440c6a32.js:9:121267)
    at Vk (framework-80ea8c0f440c6a32.js:9:99131)
    at framework-80ea8c0f440c6a32.js:9:98998
    at Jk (framework-80ea8c0f440c6a32.js:9:99005)
    at Ok (framework-80ea8c0f440c6a32.js:9:95761)
    at Fk (framework-80ea8c0f440c6a32.js:9:96150)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
Mi @ framework-80ea8c0f440c6a32.js:9
```
which, following the link, gives this expanded error message:
```
Objects are not valid as a React child (found: object with keys {message, name, stack, config, code, status}). If you meant to render a collection of children, use an array instead.
```
the only option at this point is to click "Force Quit" and reopen bruno.

This is the test script I'm using:
```js
await Promise.all(res.body.map(t => {
  console.log("Deleting " + t.id);
  return axios.delete(`${bru.getEnvVar("url")/${t.id}`)
    .then(res2 => {
      console.log("Success deleting id " + t.id);
      test(t.id, () => expect(res2.status).to.satisfy(v => {
        return v === "DELETED" || v === "DELETING";
      }));
    })
    .catch(res2 => {
      console.log("Failure: " + res2);
      test(t.id, () => expect.fail(res2));
    })
    .finally(() => {
      console.log("Done deleting " + t.id);
    });
}));
console.log("Done all");
```

Interestingly, if all the tests pass, the crash does not occur, and the tests tab and tests show up as expected. This appears to have something to do with using `async/await`, as I have not encountered this crash when there were failures normally (as in not using async/await)

### Screenshots/Live demo link

request and tests ran, 6 failures here:
![image](https://github.com/user-attachments/assets/5a256d41-fdc1-4cb7-8e38-2c3d5bb3c893)
click on Tests tab, crash:
![image](https://github.com/user-attachments/assets/33ec9582-9907-4264-8851-383cacca203b)
console view (6 occurrences of the error):
![image](https://github.com/user-attachments/assets/2d1a768e-7ed4-4cc5-9549-e4ecadb31d0a)
run again with no failures, tab can be accessed:
![image](https://github.com/user-attachments/assets/7a8f7d87-3dc1-43d2-a47b-2702f605186a)

**Comment by anusree-bruno** [comment]
Hi @jhorton-netapp,

I couldn’t reproduce the issue with my tests. Could you try it on the latest version and let me know if it’s still happening for you?

**Comment by jhorton-netapp** [comment]
Yes, this issue still occurs on 1.35.0

**Comment by anusree-bruno** [comment]
@jhorton-netapp  Could you share the collection after removing all sensitive information? It would be great if you could also include the res and res2 values or schemas.
