### ISSUE TITLE
flatpak on fedora40 in v1.25 throws UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by slartibart70** [usebruno/bruno#2894]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

just running bruno shows in the logs:

```
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:2:89409)
    at _.send (node:electron/js2c/browser_init:2:73857)
    at add (/app/extra/bruno/resources/app.asar/src/app/watcher.js:298:23)
    at FSWatcher.<anonymous> (/app/extra/bruno/resources/app.asar/src/app/watcher.js:609:34)
    at FSWatcher.emit (node:events:519:28)
    at FSWatcher.emitWithAll (/app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:632:8)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Error: Line 29, col 4:
  28 |           "type": "Invoice"
> 29 |   }
          ^
  30 | }
Expected ":"
    at parser (/app/extra/bruno/resources/app.asar/node_modules/@usebruno/lang/v2/src/bruToJson.js:629:11)
    at bruToJson (/app/extra/bruno/resources/app.asar/src/bru/index.js:113:18)
    at add (/app/extra/bruno/resources/app.asar/src/app/watcher.js:294:19)
    at FSWatcher.<anonymous> (/app/extra/bruno/resources/app.asar/src/app/watcher.js:609:34)
    at FSWatcher.emit (node:events:519:28)
    at FSWatcher.emitWithAll (/app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:632:8)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
```

There are other issues (e.g. #2144) but this one with type 'Invoice' seems new

### .bru file to reproduce the bug

none

### Screenshots/Live demo link

see log output above

**Comment by sanjai0py** [comment]
Hey, @slartibart70 will it be possible for you to share the `.bru` file?

**Comment by slartibart70** [comment]
sure

**Comment by slartibart70** [comment]
[data.txt](https://github.com/user-attachments/files/16726164/data.txt)
