### ISSUE TITLE
GUI Test Runner does not detect test cases with import

### ISSUE THREAD

**Issue by ant0x64** [usebruno/bruno#2895]
### I have checked the following:

- [X] I use the newest version of bruno. **(v1.26.1)**
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

If the test contains import of any library, Test Runner does not show the result of failed test, although if it executed individually - everything works correctly. This problem was not observed in the previous version.

### Screenshots/Live demo link

Test case individually:
![image](https://github.com/user-attachments/assets/0c58af6b-03e0-4dbb-8dfc-09bbe1d39642)

With test runner:
![image](https://github.com/user-attachments/assets/74be6052-6a45-4e1e-b819-5f586fc98fc4)
![image](https://github.com/user-attachments/assets/eefb3006-456d-43d4-bcf3-448bbfc0f05c)

**Comment by ant0x64** [comment]
With Bruno CLI it works fine:
```bash
tests/admin/authorized/auth (201 Created) - 1070 ms
   ✓ assert: res.status: eq 201
   ✓ assert: res.body.accessToken: isDefined
   ✓ Response 201 and it has a token
tests/admin/authorized/providers (200 OK) - 352 ms
[Function: AssertionError]
AssertionError: expected 200 to equal 201
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at /usr/src/app/vm.js:5:25
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at /usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/test.js:3:11
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at module.exports (/usr/src/app/vm.js:4:1)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at TestRuntime.runTests (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/runtime/test-runtime.js:155:11)
    at runSingleRequest (/usr/local/lib/node_modules/@usebruno/cli/src/runner/run-single-request.js:355:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:560:24) {
  showDiff: true,
  actual: 200,
  expected: 201,
  operator: 'strictEqual'
}
   ✕ Reponse status should be 201
tests/admin/not-authorized/auth (201 Created) - 342 ms
   ✓ assert: res.status: eq 201
   ✓ assert: res.body.accessToken: isDefined
   ✓ Response 201 and it has a token
tests/admin/not-authorized/providers (401 Unauthorized) - 232 ms
[Function: AssertionError]
AssertionError: expected 401 to equal 200
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at /usr/src/app/vm.js:4:25
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at /usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/test.js:3:11
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at module.exports (/usr/src/app/vm.js:3:1)
    at VM2 Wrapper.apply (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/vm2/lib/bridge.js:485:11)
    at TestRuntime.runTests (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/js/src/runtime/test-runtime.js:155:11)
    at runSingleRequest (/usr/local/lib/node_modules/@usebruno/cli/src/runner/run-single-request.js:355:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.handler (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:560:24) {
  showDiff: true,
  actual: 401,
  expected: 200,
  operator: 'strictEqual'
}
   ✕ Reponse status should be 200

Requests:    4 passed, 4 total
Tests:       2 passed, 2 failed, 4 total
Assertions:  4 passed, 4 total
Ran all requests - 1996 ms

Requests:    4 passed, 4 total
Tests:       2 passed, 2 failed, 4 total
Assertions:  4 passed, 4 total
Waiting for the debugger to disconnect...
```

**Comment by ant0x64** [comment]
Rolling back to the previous version resolved this issue (and many others GUI related issues)

**Comment by anusree-bruno** [comment]
This issue has been fixed in the later versions. Closing this ticket

![Image](https://github.com/user-attachments/assets/06f88359-0c16-40ff-8f1a-69014f1a4781)

![Image](https://github.com/user-attachments/assets/b5bd3f9f-feb8-4aad-8f6c-97f031d9c40f)
