### ISSUE TITLE
MacOS doesn't recognize environments & requests with spaces in name

### ISSUE THREAD

**Issue by piyh** [usebruno/bruno#294]
This is an inconsistent issue and I'm not sure what exactly triggers it.  On 13.6 Ventura, if I copy in an environment named `AE Local.bru` to a collection's environment folder, it isn't picked up in the environment dropdown.  If I rename that file in place to `AE_Local.bru` it will instantly show up in Bruno.

Additionally when I go to rename a request with spaces through Bruno UI, it will not get renamed.  If I rename the same thing with underscores instead of spaces, it goes through.

**Comment by piyh** [comment]
For now the workaround is to use underscores when things get weird.

**Comment by lared** [comment]
Let's narrow it down a bit. I tried to replicate some of the issues on v0.17.0, Ubuntu Jammy.

Via UI:

- creation of collections with spaces -> works fine
- creation of folders with spaces -> works fine
- creation of requests with spaces -> works fine
- renaming collection with spaces -> renamed just the name in `bruno.json`, but not the directory
- renaming folders with spaces -> works fine, 
- renaming requests with spaces -> works fine
- creating a new environment with spaces -> works fine

Via file system:

- dropping in a collection with spaces in name -> wasn't picked up by Bruno

**Comment by lared** [comment]
Parsing variables with spaces seems to fail:

Environment file:
```
vars {
  variable with spaces: 
}
```

```
Error sending from webFrameMain:  Error: Failed to serialize arguments
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2156)
    at addEnvironmentFile (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:112:21)
    at add (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:235:12)
    at FSWatcher.<anonymous> (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:428:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/index.js:632:8)
    at NodeFsHandler._handleFile (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:27444) UnhandledPromiseRejectionWarning: Error: Line 2, col 12:
  1 | vars {
> 2 |   variable with spaces: 
                 ^
  3 | }
Expected ":"
    at parser (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-lang/v2/src/envToJson.js:163:11)
    at bruToEnvJson (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/bru/index.js:7:18)
    at addEnvironmentFile (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:95:17)
    at add (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:235:12)
    at FSWatcher.<anonymous> (/home/lared/projects/2023-10-01_bruno_bug/bruno/packages/bruno-electron/src/app/watcher.js:428:34)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/index.js:540:8)
    at FSWatcher._emit (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/index.js:632:8)
    at NodeFsHandler._handleFile (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/lib/nodefs-handler.js:400:14)
    at NodeFsHandler._addToNodeFs (/home/lared/projects/2023-10-01_bruno_bug/bruno/node_modules/chokidar/lib/nodefs-handler.js:637:21)
```

By the way it's a royal pain in the ass to find those errors as they don't generate any output, you need to set `ELECTRON_ENABLE_LOGGING=1`, even for dev env.

**Comment by piyh** [comment]
Your ability to take my vague bug report and turn it into reproducible example with a stack trace is amazing.

**Comment by lared** [comment]
It's basically binary search, fueled by being slightly annoyed with some of my environments randomly disappearing as well. It takes no time at all to add a bunch of spaces to stuff, and if you can tell whether it happens in web or electron, you can just look at either of the logs.

There are also other issues with the parser:

variable name `writingcustomparsersishard:::::::::::::::::::::::` maps to `writingcustomparsersishard` with value `::::::::::::::::::::::`. It seems like we need to either enforce the limitations on content or modify the grammar to prevent injection attacks.

**Comment by piyh** [comment]
This seems to be beyond just spaces as I have another environment file that has no spaces in any variables or filenames and it's completely borked.

**Comment by lared** [comment]
@piyh  are you willing to share the environment? I have bruno set up for dev locally, I can troubleshoot it further.

**Comment by piyh** [comment]
Anonymized the alphabet characters, but the structure and special characters are intact
```
vars {
  ab_url: http://localhost:9090
  ac_url: http://localhost:8083
  abcd_url: http://localhost:8080
  subject1_eid: srq765
  subject2_eid: abc123
  subject3_eid: zyx987
  eid: qrs484
  DCS_role: SOME_engineering_lead_1_regression
  AB_role: division_12345_AB_regression
  DFD_role: dataset_DFD_reviewer_regression
  a_id: 1
  B_id: 11
  some_url: https://abc-zy.subdomain.company.com
  client_id: abc`2
}
vars:secret [
  one_secret,
  two_token,
  three_token
]
```

**Comment by piyh** [comment]
Getting an error trying to edit previous post, but filename was `AE_QA.bru`

**Comment by piyh** [comment]
<img width="265" alt="image" src="https://github.com/usebruno/bruno/assets/10518137/51a7d93d-35c3-49e1-98f3-3b581c08cec1">
This looks to be a "will not fix" based on the new error messages if you try to put spaces in names of env vars.

**Comment by VGerris** [comment]
I don't get any message or error when creating collections and requests and ended up here because nothing was visible. Would be nice if this gets fixed through the tool where it is impacting it. Thank you.
