### ISSUE TITLE
POST request gives white screen, error mimeType is not defined

### ISSUE THREAD

**Issue by wallmarc** [usebruno/bruno#301]
This request crashes Bruno with a white screen.

Bruno does not crash if the request is not successful (e.g. using invalid Authorization token)

```
meta {
  name: POST-jwt
  type: http
  seq: 4
}

post {
  url: https://{{host}}/app/jwt/v1
  body: json
}

headers {
  Content-Type: application/json
  Accept: application/jwt
  Authorization: Bearer 42dd7b21-d604-4c6b-b96c-8df0131635b2
}
```

The corresponding curl executes fine
```
% curl --request POST \
  --url https://[REDACTED]/app/jwt/v1 \
  --header 'Accept: application/jwt' \
  --header 'Authorization: Bearer 42dd7b21-d604-4c6b-b96c-8df0131635b2' \
  --header 'Content-Type: application/json' \
  --data '{
    [REDACTED]
}' -v
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 192.168.106.2:443...
* Connected to [REDACTED] (192.168.106.2) port 443 (#0)
* ALPN: offers h2,http/1.1
* (304) (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES256-GCM-SHA384
* ALPN: server accepted h2
* Server certificate:
[REDACTED]
* using HTTP/2
* h2 [:method: POST]
* h2 [:scheme: https]
* h2 [:authority: [REDACTED]]
* h2 [:path: /app/jwt/v1]
* h2 [user-agent: curl/8.1.2]
* h2 [accept: application/jwt]
* h2 [authorization: Bearer 42dd7b21-d604-4c6b-b96c-8df0131635b2]
* h2 [content-type: application/json]
* h2 [content-length: 150]
* Using Stream ID: 1 (easy handle 0x15d00a800)
> POST /app/jwt/v1 HTTP/2
> Host: [REDACTED]
> User-Agent: curl/8.1.2
> Accept: application/jwt
> Authorization: Bearer 42dd7b21-d604-4c6b-b96c-8df0131635b2
> Content-Type: application/json
> Content-Length: 150
>
* We are completely uploaded and fine
< HTTP/2 200
< date: Tue, 03 Oct 2023 07:55:08 GMT
< content-type: application/jwt;charset=UTF-8
< content-length: 889
< x-content-type-options: nosniff
< strict-transport-security: max-age=15724800; includeSubDomains
< x-frame-options: DENY
< x-xss-protection: 0
< referrer-policy: no-referrer
<
* Connection #0 to host [REDACTED] left intact
eyJhbGciOiJSUzI...[REDACTED]
```

Output from Developer Tools:
```
_app-8938ad8cf87c7d92.js:1 >> request cancelled
framework-49f1e091cbf6b261.js:1 ReferenceError: mimeType is not defined
    at l (_app-8938ad8cf87c7d92.js:1:524659)
    at Ot (index-df05a95536b312e2.js:1:78201)
    at Eo (framework-49f1e091cbf6b261.js:1:63194)
    at xi (framework-49f1e091cbf6b261.js:1:120434)
    at bs (framework-49f1e091cbf6b261.js:1:109370)
    at gs (framework-49f1e091cbf6b261.js:1:109298)
    at vs (framework-49f1e091cbf6b261.js:1:109161)
    at as (framework-49f1e091cbf6b261.js:1:105941)
    at ls (framework-49f1e091cbf6b261.js:1:104492)
    at S (framework-49f1e091cbf6b261.js:1:138465)
du @ framework-49f1e091cbf6b261.js:1
a.componentDidCatch.t.callback @ framework-49f1e091cbf6b261.js:1
Ua @ framework-49f1e091cbf6b261.js:1
ki @ framework-49f1e091cbf6b261.js:1
bi @ framework-49f1e091cbf6b261.js:1
yi @ framework-49f1e091cbf6b261.js:1
(anonymous) @ framework-49f1e091cbf6b261.js:1
ws @ framework-49f1e091cbf6b261.js:1
ls @ framework-49f1e091cbf6b261.js:1
S @ framework-49f1e091cbf6b261.js:1
T @ framework-49f1e091cbf6b261.js:1
_app-8938ad8cf87c7d92.js:1 {error: ReferenceError: mimeType is not defined
    at l (file:///Applications/Bruno.app/Contents/Resources…, errorInfo: {…}}
```

**Comment by helloanoop** [comment]
@wallmarc This issue has been fixed and must not happen in the latest release (v0.27.2)

**Comment by wallmarc** [comment]
Tested ok on v0.27.2
thanks!
