### ISSUE TITLE
Bruno crashes with white screen when performing a POST request

### ISSUE THREAD

**Issue by prwnr** [usebruno/bruno#3132]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When doing a POST request on latest version (v1.29.0), the app crashes compoletely and can be only force quit.
The same request worked in previous version (tested on v1.28 just now). 

This may be caused due to the fact that the API that I am calling here, returns a plain number of `5006882` for a resource creation, which is not wrapped into any JSON object - but this should be still rather considered a valid response as long as it is valid to a json parsing. 

The console log reports these errors: 
```
TypeError: Cannot create property 'modeOption' on number '5006882'
    at new CodeMirror (_app-1423f73a74fbe339.js:6:175238)
    at CodeMirror (_app-1423f73a74fbe339.js:6:175058)
    at CodeEditor.value (413-d0db79460ee22f00.js:1:152797)
    at lk (framework-80ea8c0f440c6a32.js:9:90626)
    at jk (framework-80ea8c0f440c6a32.js:9:111105)
    at framework-80ea8c0f440c6a32.js:9:111116
    at Qk (framework-80ea8c0f440c6a32.js:9:111628)
    at Hk (framework-80ea8c0f440c6a32.js:9:95039)
    at J (framework-80ea8c0f440c6a32.js:33:1364)
    at MessagePort.R (framework-80ea8c0f440c6a32.js:33:1894)
```

```
{
    "error": {},
    "errorInfo": {
        "componentStack": "\n    at CodeEditor (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:150121)\n    at QueryResult_QueryResultPreview (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:228620)\n    at div\n    at P (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:48632)\n    at ResponsePane_QueryResult (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:232575)\n    at section\n    at div\n    at P (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:48632)\n    at components_ResponsePane (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:247885)\n    at section\n    at section\n    at div\n    at P (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:48632)\n    at components_RequestTabPanel (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:455536)\n    at section\n    at div\n    at P (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:48632)\n    at div\n    at Main (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/413-d0db79460ee22f00.js:1:677586)\n    at main\n    at div\n    at Home\n    at div\n    at HotkeysProvider (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:50754)\n    at div\n    at P (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:48632)\n    at AppProvider (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:14:48976)\n    at GoldenEdtionGuardProvider (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:57605)\n    at div\n    at ToastProvider (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:14:50356)\n    at Le (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:31:46300)\n    at Theme (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:173361)\n    at components_Provider (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:24:3694)\n    at NoSsr (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:55679)\n    at div\n    at SafeHydrate (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:55579)\n    at ErrorBoundary (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:14:35412)\n    at _app (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-1423f73a74fbe339.js:17:55925)\n    at _PathnameContextProviderAdapter (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:62713)\n    at Container (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:9068)\n    at AppContainer (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:11134)\n    at Root (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-a9033015b47bbde8.js:1:14776)"
    }
}
```

### Screenshots/Live demo link

![image](https://github.com/user-attachments/assets/fa0711f0-99b6-4b5d-aea1-bcc946fe551f)

**Comment by helloanoop** [comment]
@prwnr Thanks for reporting this issue. We are working on a patch fix and will release this in the next 3 hours.

**Comment by JBlacklaws** [comment]
Has there been any progress on this? I am encountering a identical issue
![Screenshot 2024-09-25 at 12 20 36](https://github.com/user-attachments/assets/c62f2e61-e344-4eed-8b3b-91d0146977a5)
