### ISSUE TITLE
[1.36.0] Running CLI throws new Error(match.message)

### ISSUE THREAD

**Issue by fantpmas** [usebruno/bruno#3599]
### I have checked the following:

- [X] I use the newest version of bruno.
- [X] I've searched existing issues and found nothing related to my issue.

### Describe the bug

When running any .bru file via the CLI 1.36.0 I get an error, working fine with 1.35.0:
```
/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/node_modules/@usebruno/lang/v2/src/bruToJson.js:670
    throw new Error(match.message);
          ^

Error: Line 45, col 1:
  44 |         
> 45 | }
       ^
Expected end of input, "docs", "tests", "script:post-response", "script:pre-request", "assert", "vars:post-response", "vars:pre-request", "body", "body:multipart-form", "body:form-urlencoded", "body:graphql:vars", "body:graphql", "body:sparql", "body:xml", "body:text", "body:json", "auth:apikey", "auth:wsse", "auth:oauth2", "auth:digest", "auth:bearer", "auth:basic", "auth:awsv4", "headers", "params:query", "params:path", "query", "trace", "connect", "head", "options", "patch", "delete", "put", "post", "get", or "meta"
    at parser (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/node_modules/@usebruno/lang/v2/src/bruToJson.js:670:11)
    at bruToJson (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/utils/bru.js:35:18)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:141:27)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at traverse (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:120:85)
    at getFilesInOrder (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:151:24)
    at createCollectionFromPath (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:154:10)
    at Object.handler (/Users/thomasv/.asdf/installs/nodejs/18.14.0/lib/node_modules/@usebruno/cli/src/commands/run.js:444:22)

Node.js v18.14.0
```

### .bru file to reproduce the bug

```
meta {
  name: mocky
  type: http
  seq: 1
}

get {
  url: https://run.mocky.io/v3/ad186501-abbe-4f01-b029-7bd19c5105e7
  body: none
  auth: none
}
```

### Screenshots/Live demo link

![Screenshot 2024-12-06 at 08 20 41](https://github.com/user-attachments/assets/8a7a6771-3414-4e9b-9a63-c82b617e41b2)

![Screenshot 2024-12-06 at 08 21 36](https://github.com/user-attachments/assets/2a759065-f560-4d97-8fc6-709728880a3a)

**Comment by sreelakshmi-bruno** [comment]
Hi @fantpmas, seems like you've got an invalid .bru file in the collection. Can you try checking for that and remove it? Let me know how it goes. Thanks!

**Comment by fantpmas** [comment]
Having a hard time figuring out where the issue is, any pointers on how to locate the erroneous file? Note that the entire collection is running fine with 1.35.0.

**Comment by sreelakshmi-bruno** [comment]
Hi @fantpmas, 

In Bruno, watcher inspects every .bru file and will only get it listed in Bruno if its valid. Checking if every .bru file in filesystem/or in VS Code is present in Bruno can help us know which files were invalid. I understand this can get tedious, we're working on a fix to indicate invalid .bru files in Bruno. Likely this will go out in the next release. 

Thanks!

**Comment by fantpmas** [comment]
Found the file in the mean time but now have the same issue as [ca-stefan-cordes](https://github.com/ca-stefan-cordes)

**Comment by sreelakshmi-bruno** [comment]
Hi @ca-stefan-cordes, the issue you are facing has been resolved in 1.36.1. Please check it out and let me know how it goes.

@fantpmas , please check out 1.36.1 as well.

**Comment by ca-stefan-cordes** [comment]
@sreelakshmi-bruno thanks for the quick fix.
Works again fine now:

```
example-it>bru run  --insecure --env jenkins
...
Requests:    12 passed, 12 total
Tests:       12 passed, 12 total
Assertions:  0 passed, 0 total

example-it>bru run  --version
1.36.1
```

**Comment by sreelakshmi-bruno** [comment]
That's great! Closing the issue as it has been resolved.
