### ISSUE TITLE
OpenAPI spec - Range Error

### ISSUE THREAD

**Issue by Vincentv92** [usebruno/bruno#3663]
Still seeing this issue when importing Jira's OpenAPI spec: https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json?_v=1.7513.0-0.1310.0

I'm running Bruno v1.31.0

Slightly different stack trace here though:
```
RangeError: Maximum call stack size exceeded
    at resolveRefs (871-7fa6c933a094f6be.js:1:24965)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
    at 871-7fa6c933a094f6be.js:1:25210
    at Array.map (<anonymous>)
    at resolveRefs (871-7fa6c933a094f6be.js:1:25187)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
    at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
BrunoError: An error occurred while parsing the OpenAPI collection
    at 871-7fa6c933a094f6be.js:1:28585
    at new Promise (<anonymous>)
    at parseOpenApiCollection (871-7fa6c933a094f6be.js:1:27548)
```

_Originally posted by @tlund101 in https://github.com/usebruno/bruno/issues/939#issuecomment-2438452883_
           
---

For a propriety API i also run into this issue, is there something else we need to provide?

**Comment by talkingjd72** [comment]
I am running into this s well.

**Comment by sreelakshmi-bruno** [comment]
Hi, I'm able to reproduce this issue, We're investigating this. Thanks!

**Comment by sreelakshmi-bruno** [comment]
Hi, sharing quick update: this is expected to go out in the upcoming release (likely early next week).

**Comment by AndreasEK** [comment]
Nice, anything we can do in the meantime to get the file passed? I'm assuming it's a circular dependency somewhere, is it?

**Comment by sreelakshmi-bruno** [comment]
Hi, we'll share a beta build within next two days with the fix so that you can use it until we have an official release.

**Comment by sreelakshmi-bruno** [comment]
Hi, apologies for the delay, we have a [nightly build](https://github.com/usebruno/bruno-nightly-builds/releases/) for this issue, please test it and let me know how it goes. Thanks!

**Comment by Vincentv92** [comment]
For me this specific issue has been resolved, also for the propriety private API its working 👍
