### ISSUE TITLE
[Bug] When an empty secret variable is saved, environment fails to load on restart

### ISSUE THREAD

**Issue by lared** [usebruno/bruno#399]
To reproduce:

1. Create a new collection
2. Create an empty request (can't create an environment via UI without that)
3. Create a new environment within the collection
4. Add a new secret variable with no value
5. Save the variables
6. Close Bruno
7. Open Bruno
8. Go to the collection created in step one
9. The new collection doesn't show up, despite being present on disk

Stacktrace:

```
Error: Decrypt failed: unrecognized string format
    at decryptString (/home/me/bruno/packages/bruno-electron/src/utils/encryption.js:70:11)
    at /home/me/bruno/packages/bruno-electron/src/app/watcher.js:142:28
    at arrayEach (/home/me/bruno/node_modules/lodash/lodash.js:530:11)
    at Function.forEach (/home/me/bruno/node_modules/lodash/lodash.js:9410:14)
    at changeEnvironmentFile (/home/me/bruno/packages/bruno-electron/src/app/watcher.js:138:9)
    at change (/home/lared/projects/me/bruno/packages/bruno-electron/src/app/watcher.js:341:12)
    at FSWatcher.<anonymous> (/home/me/bruno/bruno/packages/bruno-electron/src/app/watcher.js:431:37)
    at FSWatcher.emit (node:events:527:28)
    at FSWatcher.emitWithAll (/home/me/bruno/node_modules/chokidar/index.js:540:8)
    at awfEmit (/home/me/bruno/node_modules/chokidar/index.js:607:14)
```

**Comment by lared** [comment]
By the way why would you even have those variables - for instance for env variables populated by scripts (you can't create they by script, #295

**Comment by lared** [comment]
Resolved in the recent version, thanks!
