### ISSUE TITLE
[bruno cli] Error bruToJson.js:460

### ISSUE THREAD

**Issue by wiquanAppD** [usebruno/bruno#446]
Error running using CLI. 
Works fine with IDE.

version: 0.13.0

```bash
$ bru run --output results.json --env druid
Running Folder Recursively

/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/lang/v2/src/bruToJson.js:460
    throw new Error(match.message);
          ^

Error: Line 16, col 1:
  15 | }
> 16 | d
       ^
  17 | tests {
Expected end of input, "docs", "tests", "script:post-response", "script:pre-request", "assert", "vars:post-response", "vars:pre-request", "body", "body:multipart-form", "body:form-urlencoded", "body:graphql:vars", "body:graphql", "body:xml", "body:text", "body:json", "auth:bearer", "auth:basic", "headers", "query", "trace", "connect", "head", "options", "patch", "delete", "put", "post", "get", or "meta"
    at parser (/usr/local/lib/node_modules/@usebruno/cli/node_modules/@usebruno/lang/v2/src/bruToJson.js:460:11)
    at bruToJson (/usr/local/lib/node_modules/@usebruno/cli/src/utils/bru.js:21:18)
    at traverse (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:129:27)
    at traverse (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:118:11)
    at traverse (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:118:11)
    at getFilesInOrder (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:147:5)
    at getBruFilesRecursively (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:151:10)
    at Object.handler (/usr/local/lib/node_modules/@usebruno/cli/src/commands/run.js:339:20)

Node.js v18.17.1
```

**Comment by helloanoop** [comment]
@wiquanAppD Need a bit more details to debug.

Can you share the request `.bru` file where this is happening. You can mask/replace the sensitive parts in your file.

Also, you can try to see if this is happening in `v0.14.0`

**Comment by wiquanAppD** [comment]
Sorry please disregard. This was simply a typo.
