### ISSUE TITLE
Apple Silicon: Empty blank windows on start

### ISSUE THREAD

**Issue by christhomas** [usebruno/bruno#487]
When I downloaded the latest release v0.22.0 on my apple m2 pro using the apple silicon version and started it, all I get is a blank empty white window. Has anybody else seen this problem before or have any advice that I can try?

<img width="1287" alt="Screenshot 2023-10-09 at 18 28 16" src="https://github.com/usebruno/bruno/assets/827996/70a35cc1-036a-4ef6-9fdc-7318ced9c0d9">

**Comment by christhomas** [comment]
I also tried a few older releases back to 0.17 and including some of the versions using the x64 build and none of them worked. All of them produced a white screen like above.

**Comment by helloanoop** [comment]
Can you open developer tools (you can open them from the menu bar) and see if there are any logs ?

**Comment by christhomas** [comment]
There is a user interface here, but it's not painting anything and I can click on the open developer tools menu item, but nothing appears. However if I roll the mouse over the window and see a little hand icon and click it, it'll open github for example.

So there is a user interface. But some reason, just not visible and I can't see the developer tools to be able to use it.

**Comment by Kage-Yami** [comment]
I'm seeing the same symptoms (blank screen, but in certain spots the cursor changes, suggesting the presence of an underlying-but-invisible GUI) on Arch Linux (so an x86_64 system), using both the AppImage downloaded from the website, and the `bruno-bin` AUR package (which uses an extracted copy of the official `.deb` package).

If I run the AppImage from a terminal, this is printed:

<details>
<summary>Terminal Output</summary>

```log
    ~/apps/bruno ▓▒░
❯ ./bruno.AppImage

Preferences file is located at: /home/yami/.config/bruno/preferences.json
[708042:1014/194405.923629:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[708042:1014/194405.923677:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
[708077:1014/194406.015691:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708077:1014/194406.015785:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708077:1014/194406.015821:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Maximum number of clients reached
[708077:1014/194406.018385:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708077:1014/194406.018471:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708077:1014/194406.018511:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[708077:1014/194406.018547:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[708077:1014/194406.034196:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
(node:708042) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
    at exports.setContentSecurityPolicy (/tmp/.mount_bruno.w66Exx/resources/app.asar/node_modules/electron-util/index.js:150:9)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:708042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
[708103:1014/194406.244054:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708103:1014/194406.244146:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708103:1014/194406.244184:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Maximum number of clients reached
[708103:1014/194406.244299:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708103:1014/194406.244345:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708103:1014/194406.244385:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[708103:1014/194406.244420:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[708103:1014/194406.245801:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
[708110:1014/194406.271104:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708110:1014/194406.271195:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708110:1014/194406.271237:ERROR:gl_display.cc(920)] eglInitialize OpenGL failed with error EGL_NOT_INITIALIZED, trying next display type
Maximum number of clients reached
[708110:1014/194406.271360:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Could not open the default X display.
[708110:1014/194406.271405:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Could not open the default X display.
[708110:1014/194406.271454:ERROR:gl_display.cc(920)] eglInitialize OpenGLES failed with error EGL_NOT_INITIALIZED
[708110:1014/194406.271491:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[708110:1014/194406.272828:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
Maximum number of clients reached
[708117:1014/194406.290629:ERROR:angle_platform_impl.cc(43)] DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
ERR: DisplayVkXcb.cpp:59 (initialize): xcb_connect() failed, error 1
[708117:1014/194406.290762:ERROR:angle_platform_impl.cc(43)] Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
ERR: Display.cpp:997 (initialize): ANGLE Display::initialize error 12289: Not initialized.
[708117:1014/194406.290825:ERROR:gl_display.cc(508)] EGL Driver message (Critical) eglInitialize: Not initialized.
[708117:1014/194406.290870:ERROR:gl_display.cc(920)] eglInitialize SwANGLE failed with error EGL_NOT_INITIALIZED
[708117:1014/194406.290926:ERROR:gl_ozone_egl.cc(23)] GLDisplayEGL::Initialize failed.
[708117:1014/194406.292545:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
Maximum number of clients reached
Maximum number of clients reached
[708124:1014/194406.306968:ERROR:gpu_init.cc(521)] Passthrough is not supported, GL is disabled, ANGLE is 
[708124:1014/194406.340322:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 530579459
```
</details>

Desktop environment is Cinnamon 5.8.4, so using X, not Wayland. GPU is dedicated AMD. Not sure what other information might be relevant for this issue.

**Comment by christhomas** [comment]
You know what, for some reason now, it's working. The screen came back and I can use the app. I have no explanation for the problem

<img width="1029" alt="Screenshot 2023-10-14 at 11 59 52" src="https://github.com/usebruno/bruno/assets/827996/377d55ed-245a-42e4-b6a7-fc3b3af135f9">

**Comment by Kage-Yami** [comment]
... I can't believe I can say the same thing, too. My system randomly decided to fall over shortly after my previous comment, requiring me to hold down the power button just to reset it properly. And now, the Bruno 0.24.0 AppImage is working fine...

For reference, these are the logs (no "could not open the default X display" errors printed):

<details>
<summary>Terminal Output</summary>

```log
Preferences file is located at: /home/yami/.config/bruno/preferences.json
[5790:1014/200547.143751:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface “org.freedesktop.portal.FileChooser”
[5790:1014/200547.143798:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
(node:5790) UnhandledPromiseRejectionWarning: Error: Each line must end in a semicolon
    at exports.setContentSecurityPolicy (/tmp/.mount_bruno_PPUhoz/resources/app.asar/node_modules/electron-util/index.js:150:9)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:5790) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
</details>

**Comment by christhomas** [comment]
Alright, that doesn't explain why on my macbook it was having a similar problem. But maybe it's doing the mac version of that

**Comment by lutherjohnrichards** [comment]
Having the same issue. Any idea on how to solve?

**Comment by helloanoop** [comment]
@lutherjohnrichards Can you share more details.

1. Which mode of installation did you use (brew / binary) ?
2. Can you check if there are any errors in console. You can do this by toggling dev tools `View -> Toggle Developer Tools` in menubar

**Comment by lutherjohnrichards** [comment]
@helloanoop  Thanks for the speedy response.
Used brew.
No errors/output in console.

**Comment by helloanoop** [comment]
Can you try opening Bruno from command line like below to see any errors being logged

`open -W --stdout $(tty) --stderr $(tty) /Applications/Bruno.app`

![image](https://github.com/usebruno/bruno/assets/9350733/03c6fa24-60b6-460f-9e65-06be18ba9fe2)

**Comment by lutherjohnrichards** [comment]
Woah okay. Think I found the error xD

<img width="856" alt="Screenshot 2023-11-29 at 22 57 17" src="https://github.com/usebruno/bruno/assets/97586872/9fea3550-530e-40e5-a67f-5c58b4bc610f">

**Comment by lutherjohnrichards** [comment]
The rest of my system is working perfectly, so not sure it's a machine issue.

**Comment by helloanoop** [comment]
Closing this issue as there have been no recent occurrences.
