### ISSUE TITLE
Bug: application window does not appear

### ISSUE THREAD

**Issue by jeettrivedi** [usebruno/bruno#581]
After installing via snap, I receive the following error
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/snap/bruno/2/resources/app.asar/node_modules/@usebruno/query/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/bruno/2/resources/app.asar/node_modules/@usebruno/js/src/utils.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

(bruno:104853): Gtk-WARNING **: 14:47:47.412: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 14:47:47.426: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:47:47.426: Failed to load module "window-decorations-gtk-module"
```
For context, I am using Pop OS with KDE desktop environment and bspwm window manager. 

Happy to provide additional details to help with debugging.

**Comment by jericirenej** [comment]
I have the same issue when installing via snap. Gnome desktop (X11), Ubuntu 22.04.

**Comment by Podesta** [comment]
The problem persists on latest snap 0.25.0, under Ubuntu 22.04
```
bruno              0.25.0                      3      latest/stable    helloanoop     -
```

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/snap/bruno/3/resources/app.asar/node_modules/@usebruno/query/dist/cjs/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:360:19)
    at Module._findPath (node:internal/modules/cjs/loader:573:18)
    at Module._resolveFilename (node:internal/modules/cjs/loader:926:27)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/snap/bruno/3/resources/app.asar/node_modules/@usebruno/js/src/utils.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

(bruno:26639): Gtk-WARNING **: 14:39:36.940: Theme parsing error: gtk.css:3536:25: 'font-feature-settings' is not a valid property name
Gtk-Message: 14:39:36.958: Failed to load module "colorreload-gtk-module"
Gtk-Message: 14:39:36.958: Failed to load module "window-decorations-gtk-module"
/usr/share/libdrm/amdgpu.ids: No such file or directory
```

**Comment by jeettrivedi** [comment]
I attempted to build from source as well as run from source in dev mode and received an identical error.

**Comment by perskes** [comment]
> I have the same issue when installing via snap. Gnome desktop (X11), Ubuntu 22.04.

I second that, bruno does not start when installed via snap.
Installing it via http://debian.usebruno.com bruno/stable (apt) works fine tho, see the "Apt" section below if you are in dire need to make it work:
https://www.usebruno.com/downloads
