### ISSUE TITLE
Requests in Collection shows empty

### ISSUE THREAD

**Issue by Anandh003** [usebruno/bruno#627]
I am using Ubuntu `Ubuntu 20.04.6 LTS`. Bruno Version: `v0.16.2`

I have created some request in a collection but it is not visible. I could find files in saved location.

I have attached screenshot for better understanding

![Explorer](https://github.com/usebruno/bruno/assets/34986641/af3a994b-97a4-4aa2-9073-0ca249ec6e8a)

![Bruno](https://github.com/usebruno/bruno/assets/34986641/572f5e4e-c3ea-4e8c-ab97-0b5605923dfd)

**Comment by helloanoop** [comment]
Can you update to the latest version v0.25.0

Also, if your example does not have any sensitive info, can you share the contents of Example.bru

**Comment by skyd0me** [comment]
Same issue for me. Bruno is located on windows and the collection is in WSL (Ubuntu). I can see the empty folders but the requests are not showing up.
I`m on v0.25.0
When I copy over the files from wsl to windows, everything can be loaded so I would guess its either a windows > wsl connection issue or an Ubuntu related issue as [Anandh003](https://github.com/Anandh003) has the same issue running purely on Ubuntu

**Comment by jangernert** [comment]
Same issue on Fedora Silverblue 40 (no WSL involved)

It always happens when I have a few instances of VS Code open

```
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:617:16)
    at async /app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(Use `bruno --trace-warnings ...` to show where the warning was created)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf/asf.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf/bruno.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleDir (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:567:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:617:16)
    at async /app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/External Identifier.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/External Identifier2.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/Measure.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/Weight.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/bruno.json'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
(node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/settings.bru'
    at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
    at Object.watch (node:fs:2469:36)
    at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
    at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
    at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
    at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
    at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
(node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
```

**Comment by Its-treason** [comment]
> Same issue on Fedora Silverblue 40 (no WSL involved)
> 
> It always happens when I have a few instances of VS Code open
> 
> ```
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleDir (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:567:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:617:16)
>     at async /app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:451:21
>     at async Promise.all (index 0)
> (Use `bruno --trace-warnings ...` to show where the warning was created)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf/asf.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/asdf/bruno.json'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleDir (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:567:19)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:617:16)
>     at async /app/extra/bruno/resources/app.asar/node_modules/chokidar/index.js:451:21
>     at async Promise.all (index 0)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/External Identifier.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/External Identifier2.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/Measure.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/Weight.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 8)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/bruno.json'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)
> (node:3) UnhandledPromiseRejectionWarning: Error: EMFILE: too many open files, watch '/var/home/jangernert/Documents/MetriX-REST/settings.bru'
>     at FSWatcher.<computed> (node:internal/fs/watchers:247:19)
>     at Object.watch (node:fs:2469:36)
>     at createFsWatchInstance (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:119:15)
>     at setFsWatchListener (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:166:15)
>     at NodeFsHandler._watchWithNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:331:14)
>     at NodeFsHandler._handleFile (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:395:23)
>     at NodeFsHandler._addToNodeFs (/app/extra/bruno/resources/app.asar/node_modules/chokidar/lib/nodefs-handler.js:637:21)
> (node:3) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
> ```

@jangernert Update your system config see: https://stackoverflow.com/a/60881735

An application is planned for the next release. But good thing you send your log, because the workound was only listening for the error code `ENOSPC` and not for `EMFILE` the code you got.

**Comment by jangernert** [comment]
Thanks for the fast reply. I already increased the file limit after finding the cause for the missing sidebar entries.

**Comment by helloanoop** [comment]
@jangernert Could you check if this is still happening with the latest version of Bruno - `v1.35.0`

**Comment by jangernert** [comment]
No, haven't encountered the issue in quite a while.

**Comment by helloanoop** [comment]
Closing this issue as this no longer reproducible.
