### ISSUE TITLE
Linux AppImage Failing

### ISSUE THREAD

**Issue by john-okeefe** [usebruno/bruno#751]
OS: OpenSuse Tumbleweed
Version: Bruno 0.27.1 AppImage
Error
```
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'chai-string'
Require stack:
- /tmp/.mount_bruno_vWEyd1/resources/app.asar/node_modules/@usebruno/js/src/runtime/assert-runtime.js
- /tmp/.mount_bruno_vWEyd1/resources/app.asar/node_modules/@usebruno/js/src/index.js
- /tmp/.mount_bruno_vWEyd1/resources/app.asar/src/ipc/network/index.js
- /tmp/.mount_bruno_vWEyd1/resources/app.asar/src/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_bruno_vWEyd1/resources/app.asar/node_modules/@usebruno/js/src/runtime/assert-runtime.js:10:10)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
libva error: vaGetDriverNames() failed with unknown libva error
[25535:1023/152239.805974:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNames() failed with unknown libva error
[25554:1023/152239.886624:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

libcurl4 is installed
```
zypper search -s libcurl
Loading repository data...
Reading installed packages...

S  | Name                | Type    | Version   | Arch   | Repository
---+---------------------+---------+-----------+--------+----------------------
i+ | libcurl-devel       | package | 8.4.0-1.1 | x86_64 | Main Repository (OSS)
   | libcurl-devel-32bit | package | 8.4.0-1.1 | x86_64 | Main Repository (OSS)
i  | libcurl4            | package | 8.4.0-1.1 | x86_64 | Main Repository (OSS)
   | libcurl4-32bit      | package | 8.4.0-1.1 | x86_64 | Main Repository (OSS)
```

**Comment by john-okeefe** [comment]
I extracted the AppImage and copied my systems libcurl.so.4 to the squash-fs/usr/lib directory and that made the first part go away. Now we still have the chai-string exception.

'
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'chai-string'
Require stack:
- /home/nymusicman/Applications/squashfs-root/resources/app.asar/node_modules/@usebruno/js/src/runtime/assert-runtime.js
- /home/nymusicman/Applications/squashfs-root/resources/app.asar/node_modules/@usebruno/js/src/index.js
- /home/nymusicman/Applications/squashfs-root/resources/app.asar/src/ipc/network/index.js
- /home/nymusicman/Applications/squashfs-root/resources/app.asar/src/index.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13339)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/nymusicman/Applications/squashfs-root/resources/app.asar/node_modules/@usebruno/js/src/runtime/assert-runtime.js:10:10)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)
libva error: vaGetDriverNames() failed with unknown libva error
[28266:1023/153340.547164:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNames() failed with unknown libva error
[28286:1023/153340.588992:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
'

I should also note that this OpenSuse installation is running in a Qemu VM.

**Comment by john-okeefe** [comment]
Also wanted to note: bruno_0.27.0_x86_64_linux.AppImage works just fine on this same system.

**Comment by ChrisMayer-HEB** [comment]
This error also appears on the `Mac Apple Silicon` download.

**Comment by jwetzell** [comment]
I can confirm this same behavior using the `.deb` and `.exe` on Ubuntu 23.04 and Windows 10 respectively. Seems related to the [package.json](https://github.com/usebruno/bruno/blob/586e26fa2ecf5c7a389f5b5cf9804455a5f071db/packages/bruno-electron/package.json#L23) for the electron launcher not referencing the latest version of `@usebruno/js`.

When I update this version and rebuild the electron launcher from source (main branch) the error is no longer there.

**Comment by l0new4nder3r** [comment]
Same issue on Intel mac as well, right after latest update

<img width="493" alt="Capture d’écran 2023-10-23 à 22 52 31" src="https://github.com/usebruno/bruno/assets/27144372/71793715-4c93-4e11-b348-9a792d95ca76">

**Comment by jwetzell** [comment]
I just opened a PR that should fix this issue but will require the Bruno to cut a new release (hopefully take the 0.27.1 release down as well).

**Comment by helloanoop** [comment]
Apologies everyone for the hiccup.

Cutting a release with the fix now.

**Comment by helloanoop** [comment]
This issue affects `v0.27.1`

#### Windows Users:
Please upgrade to the latest binary `v0.27.2`

#### Linux Users:
Snap, Deb builds + Linux binaries are available for `v0.27.2`

#### Mac Users
Binaries are available for `v0.27.2`
If you are using homebrew, please use `brew install bruno@0.27.0` until the hombrew cask gets updated with the fix

cc @john-okeefe @ChrisMayer-HEB @l0new4nder3r

**Comment by l0new4nder3r** [comment]
All good with the 0.27.2 :)
Thanks for the quick fix!

**Comment by john-okeefe** [comment]
It's working great now. Thanks so much for so a quick resolution!
