### ISSUE TITLE
Unable to delete client certificates in mac desktop app

### ISSUE THREAD

**Issue by neonidian** [usebruno/bruno#858]
Clicking on the delete button icon for mis configured client certificates, displays a type error:

```
Oops! Something went wrong

TypeError: r.clientCertificates.filter is not a function

TypeError: r.clientCertificates.filter is not a function
    at p (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/117-f33df4e01bdc0d95.js:1:144574)
    at onClick (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/117-f33df4e01bdc0d95.js:1:128271)
    at Object.Oe (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:16876)
    at Ae (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:17030)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:36930
    at Ir (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:37024)
    at Ur (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:37439)
    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:42881
    at ss (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:106550)
    at Le (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:16008)
```

**Comment by helloanoop** [comment]
This issue should not be present in the latest release of Bruno. Can you check after upgrading to the latest release ?

**Comment by neonidian** [comment]
Upgraded to the latest version and i am able to delete the certificates now. Thanks!
