### ISSUE TITLE
[Bug] Bruno crashes when opening a GraphQL request

### ISSUE THREAD

**Issue by 4lch4** [usebruno/bruno#875]
I tried creating a GraphQL request for the GitHub API and now whenever I open the request, Bruno crashes and shows an all white window (screenshot at the end).

I created the request with the following options, and I've also included the Bruno file.

![Create Request dialog options](https://github.com/usebruno/bruno/assets/6931731/d1cd337f-1283-40b9-90b8-590d2f827b3b)

Bruno File:

```
meta {
  name: Get Repos
  type: graphql
  seq: 1
}

post {
  url: https://github.com
  body: none
  auth: none
}
```

![All White Bruno window](https://github.com/usebruno/bruno/assets/6931731/1b09cfef-6f58-47f2-ad1c-84e8a7045e14)

_Note: I'm on Bruno v1.0.0._

**Comment by 4lch4** [comment]
Just in case it helps, I thought of this after the fact but I opened the DevTools console, opened the request that crashes Bruno, and got the following in the logs:

![Console Logs](https://github.com/usebruno/bruno/assets/6931731/4285a6d0-1cf4-4ba7-a0a9-a526b1012a84)

```
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Fs (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:116899)
    at d (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:58070)
    at h (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:59431)
    at e (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:61492)
    at wu (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:73208)
    at xi (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:122261)
    at bs (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109370)
    at gs (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109298)
    at vs (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:109161)
    at as (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/framework-49f1e091cbf6b261.js:1:105941)
```

```json
{
    "error": {},
    "errorInfo": {
        "componentStack": "\n    at div\n    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:441998\n    at file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:444639\n    at div\n    at M (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at Ot (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:445800)\n    at div\n    at Xt (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:83729)\n    at div\n    at div\n    at M (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at $t (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:85187)\n    at div\n    at section\n    at section\n    at div\n    at M (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at to (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:177958)\n    at section\n    at div\n    at M (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at div\n    at Ii (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/916-5dd5fda478436956.js:1:238427)\n    at main\n    at div\n    at u\n    at div\n    at Ar (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:555572)\n    at div\n    at M (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1089488)\n    at he (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:518218)\n    at div\n    at ge (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:519260)\n    at Te (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1087577)\n    at v (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:608097)\n    at l (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:1050323)\n    at Rr (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558663)\n    at div\n    at Pr (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558566)\n    at r (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:480388)\n    at Ir (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/pages/_app-f453387a6c4276a5.js:1:558778)\n    at r (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:6769)\n    at Y (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:8704)\n    at ie (file:///Applications/Bruno.app/Contents/Resources/app.asar/web/_next/static/chunks/main-ad5649da2d8f61d3.js:1:11344)"
    }
}
```

**Comment by helloanoop** [comment]
@4lch4 Can you update to 1.1.0 which was just released a few minutes ago.

The graphql issue has been fixed in the latest release

**Comment by 4lch4** [comment]
Just updated and can confirm it's been fixed. Thank you!
