### ISSUE TITLE
Importing OpenApi document fails - Range Error

### ISSUE THREAD

**Issue by AuTrevor** [usebruno/bruno#939]
### What I was trying to do

Import a 1600 line published openAPI document into Bruno

### What was supposed to happen

OpenAPI was imported successfully

### What happened

UI threw and error saying: Import collection failed. An error occurred while parsing the openAPI collection. Both importing as JSON and converting to YAML and attempting to import run into similar errors.

### Additional information

Opening the console, the following error is shown:

BrunoError: An error occurred while parsing the OpenAPI collection
    at 772-5e0c4231fc48a067.js:1:25651
    at new Promise (<anonymous>)
    at ie (772-5e0c4231fc48a067.js:1:24060)
(anonymous) @ 772-5e0c4231fc48a067.js:1
Promise.catch (async)
(anonymous) @ 772-5e0c4231fc48a067.js:1
se @ 772-5e0c4231fc48a067.js:1
onClick @ 772-5e0c4231fc48a067.js:1
Oe @ framework-49f1e091cbf6b261.js:1
Ae @ framework-49f1e091cbf6b261.js:1
(anonymous) @ framework-49f1e091cbf6b261.js:1
Ir @ framework-49f1e091cbf6b261.js:1
Ur @ framework-49f1e091cbf6b261.js:1
(anonymous) @ framework-49f1e091cbf6b261.js:1
ss @ framework-49f1e091cbf6b261.js:1
Le @ framework-49f1e091cbf6b261.js:1
Hr @ framework-49f1e091cbf6b261.js:1
Kn @ framework-49f1e091cbf6b261.js:1
Qn @ framework-49f1e091cbf6b261.js:1

772-5e0c4231fc48a067.js:1 RangeError: Maximum call stack size exceeded
    at String.startsWith (<anonymous>)
    at e (772-5e0c4231fc48a067.js:1:23724)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23922)
    at e (772-5e0c4231fc48a067.js:1:23950)
    at e (772-5e0c4231fc48a067.js:1:23950)

I've validated the OpenAPI spec on the https://editor.swagger.io/.

OpenAPI spec that causes the issue is published here:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2023-09-01-preview/inference.json

**Comment by sanjai0py** [comment]
Closing this issue as it could not be recreated in the latest version of Bruno [v1.20.0](https://github.com/usebruno/bruno/releases/tag/v1.20.0) 

https://github.com/usebruno/bruno/assets/84461672/f8f9a47b-70f5-48dc-ab38-a43cc3e15b5a

**Comment by tlund101** [comment]
Still seeing this issue when importing Jira's OpenAPI spec: https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json?_v=1.7513.0-0.1310.0

I'm running Bruno v1.31.0

**Comment by pranavburnwal** [comment]
> Still seeing this issue when importing Jira's OpenAPI spec: [dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json?_v=1.7513.0-0.1310.0](https://dac-static.atlassian.com/cloud/jira/platform/swagger-v3.v3.json?_v=1.7513.0-0.1310.0)
> 
> I'm running Bruno v1.31.0
> 
> Slightly different stack trace here though:
> 
> ```
> RangeError: Maximum call stack size exceeded
>     at resolveRefs (871-7fa6c933a094f6be.js:1:24965)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
>     at 871-7fa6c933a094f6be.js:1:25210
>     at Array.map (<anonymous>)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:25187)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
>     at resolveRefs (871-7fa6c933a094f6be.js:1:26496)
> BrunoError: An error occurred while parsing the OpenAPI collection
>     at 871-7fa6c933a094f6be.js:1:28585
>     at new Promise (<anonymous>)
>     at parseOpenApiCollection (871-7fa6c933a094f6be.js:1:27548)
> ```

+1

**Comment by talkingjd72** [comment]
I am running into this issue as well with this openAPI v3 api import. 
[folio-api-json.json](https://github.com/user-attachments/files/18171194/folio-api-json.json)

**Comment by gskornowicz** [comment]
The same issue.
Trying to import this [https://github.com/cloudflare/api-schemas/blob/main/openapi.json](https://github.com/cloudflare/api-schemas/blob/main/openapi.json)
and receive
`Import collection failed: An error occurred while parsing the OpenAPI collection`

v1.38.1 installed via choco on win10
```
electron | : 33.2.1
chrome | : 130.0.6723.137
node | : 20.18.1
v8 | : 13.0.245.19-electron.0
```

Stack from console
```
index.1962d89a.js:4 RangeError: Maximum call stack size exceeded
    at new Set (<anonymous>)
    at iS (index.1962d89a.js:4:8484)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
    at iS (index.1962d89a.js:4:8474)
(anonymous) @ index.1962d89a.js:4
iU @ index.1962d89a.js:4
Promise.then
(anonymous) @ index.1962d89a.js:4
iT @ index.1962d89a.js:4
s @ index.1962d89a.js:4
uU @ lib-react.41929aa2.js:2
(anonymous) @ lib-react.41929aa2.js:2
tC @ lib-react.41929aa2.js:2
uW @ lib-react.41929aa2.js:2
sK @ lib-react.41929aa2.js:2
sQ @ lib-react.41929aa2.js:2
index.1962d89a.js:4 BrunoError: An error occurred while parsing the OpenAPI collection
    at index.1962d89a.js:4:10282
    at new Promise (<anonymous>)
    at iU (index.1962d89a.js:4:9308)
(anonymous) @ index.1962d89a.js:4
Promise.catch
(anonymous) @ index.1962d89a.js:4
iT @ index.1962d89a.js:4
s @ index.1962d89a.js:4
uU @ lib-react.41929aa2.js:2
(anonymous) @ lib-react.41929aa2.js:2
tC @ lib-react.41929aa2.js:2
uW @ lib-react.41929aa2.js:2
sK @ lib-react.41929aa2.js:2
sQ @ lib-react.41929aa2.js:2

```

**Comment by FreeSoftwareServers** [comment]
I'm still having this trying to import open AI specs

**Comment by anusree-bruno** [comment]
@FreeSoftwareServers What is the error that you are seeing? would it be possible for you to share more info?

**Comment by anusree-bruno** [comment]
> The same issue. Trying to import this https://github.com/cloudflare/api-schemas/blob/main/openapi.json and receive `Import collection failed: An error occurred while parsing the OpenAPI collection`
> 
> v1.38.1 installed via choco on win10
> 
> ```
> electron | : 33.2.1
> chrome | : 130.0.6723.137
> node | : 20.18.1
> v8 | : 13.0.245.19-electron.0
> ```
> 
> Stack from console
> 
> ```
> index.1962d89a.js:4 RangeError: Maximum call stack size exceeded
>     at new Set (<anonymous>)
>     at iS (index.1962d89a.js:4:8484)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
>     at iS (index.1962d89a.js:4:8474)
> (anonymous) @ index.1962d89a.js:4
> iU @ index.1962d89a.js:4
> Promise.then
> (anonymous) @ index.1962d89a.js:4
> iT @ index.1962d89a.js:4
> s @ index.1962d89a.js:4
> uU @ lib-react.41929aa2.js:2
> (anonymous) @ lib-react.41929aa2.js:2
> tC @ lib-react.41929aa2.js:2
> uW @ lib-react.41929aa2.js:2
> sK @ lib-react.41929aa2.js:2
> sQ @ lib-react.41929aa2.js:2
> index.1962d89a.js:4 BrunoError: An error occurred while parsing the OpenAPI collection
>     at index.1962d89a.js:4:10282
>     at new Promise (<anonymous>)
>     at iU (index.1962d89a.js:4:9308)
> (anonymous) @ index.1962d89a.js:4
> Promise.catch
> (anonymous) @ index.1962d89a.js:4
> iT @ index.1962d89a.js:4
> s @ index.1962d89a.js:4
> uU @ lib-react.41929aa2.js:2
> (anonymous) @ lib-react.41929aa2.js:2
> tC @ lib-react.41929aa2.js:2
> uW @ lib-react.41929aa2.js:2
> sK @ lib-react.41929aa2.js:2
> sQ @ lib-react.41929aa2.js:2
> ```

This issue has been fixed. I was able to open the linked spec in Bruno without any issues.

I’ll go ahead and close this issue. If you encounter any other problems, please create a new issue and include sufficient info to reproduce the problem.
